### ISSUE TITLE
Identify outreach and collaborators

### ISSUE THREAD

**Issue by hepplerj** [endangereddataweek/resources#13]
We'll be identifying those to reach out to and who might be potential collaborators with EDW.

What's the first step in getting that list? 

- [ ] Reaching out to core people
- [ ] Reaching out to core organizations
- [ ] Reaching out to wider group for the survey

**Comment by rachmattson** [comment]
DLF Government Records Transparency & Accountability interest group

**Comment by rachmattson** [comment]
NOTE: I sent
