### ISSUE TITLE
Sticker file is too small

### ISSUE THREAD

**Issue by jellenf** [endangereddataweek/resources#29]
The PNG of the sticker image is too small to print (per the Sticker Robot folks) at their minimum die cut size.

Is there a larger file (or a vectored image) that someone can share?

**Comment by hepplerj** [comment]
Thanks for getting in touch, @jellenf! Let me look into it and see what I can find out.

**Comment by kekoziar** [comment]
Any chance of getting a hi res oblong design, with the text to the right of the logo?

**Comment by brandontlocke** [comment]
@kekoziar I am not much of a designer, but I can give it a shot. You are also welcome to edit this however you'd like!

**Comment by jalbertbowden** [comment]
![endangered-data-week-logotype-horizontal](https://user-images.githubusercontent.com/46432/52169035-06dada00-2700-11e9-83f5-5279e632ce19.png)

**Comment by jellenf** [comment]
Thank you! Stickers ordered! Mischief managed!
