### ISSUE TITLE
Rewriting the README 

### ISSUE THREAD

**Issue by hepplerj** [endangereddataweek/resources#5]
As per [the guidelines with Open Leaders](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), we need to work on rewriting our README which, right now, is pretty bare bones. 

We need to answer:

- [x] what you're doing, for who, and why
- [x] what makes your project special and exciting
- [x] how to get started
- [x] where to find key resources

🚨Avoid jargon🚨

**Comment by brandontlocke** [comment]
I made a few minor changes (which Github helpfully documents!). The only major-ish thing I changed was "PRs Welcome" to "Contributions Welcome." I didn't understand what that meant until I hovered on the link, and I would imagine that others wouldn't either?
